use sakila;
-- Question 1:  Retrieve the total number of rentals made in the Sakila database
select count(rental_id) as Total_rental from rental;

-- Question 2: Find the average rental duration (in days) of movies rented from the Sakila database.
select avg(rental_duration) As average_rental_duration from film;

-- Question 3: Display the first name and last name of customers in uppercase. 
SELECT UPPER(first_name) AS upper_first_name, UPPER(last_name) AS upper_last_name
FROM customer;

-- Question 4: Extract the month from the rental date and display it alongside the rental ID.
select rental_id, month(rental_date) AS rental_month  from rental;

-- Question 5: Retrieve the count of rentals for each customer (display customer ID and the count of rentals). 
select customer_id, count(rental_id) AS Count_of_rentals
from rental group by customer_id;

-- Question 6: Find the total revenue generated by each store.
select s.store_id, sum(amount) from store s	
join staff st on s.store_id = st.store_id
join payment p on st.staff_id = p.staff_id
group by s.store_id;

-- Question 7: Display the title of the movie, customer s first name, and last name who rented it. 
select film.title As movie_title, customer.first_name, customer.last_name from rental
join inventory on rental.inventory_id = inventory.inventory_id
join film on inventory.film_id = film.film_id
join customer on rental.customer_id = customer.customer_id;

-- Question 9: Retrieve the names of all actors who have appeared in the film "Gone with the Wind."
select actor.first_name, actor.last_name
from actor
join film_actor on actor.actor_id = film_actor.actor_id
join film on film_actor.film_id = film.film_id
where film.title = 'Gone with the wind';

-- Question 10: Determine the total number of rentals for each category of movies. 
select fc.category_id, count(r.rental_id) as total_number
from rental r join inventory i on r.inventory_id = i.inventory_id
join film f on i.film_id = f.film_id
join film_category fc on f.film_id = fc.film_id
group by fc.category_id;

-- Question 11: Find the average rental rate of movies in each language.
select l.name as language, avg(f.rental_rate) as avg_rental_rate
from film f join language l on f.language_id = l.language_id
group by l.name;

-- Question 12: Retrieve the customer names along with the total amount they've spent on rentals. 
select sum(p.amount) as Amount,concat(c.first_name, ' ', c.last_name) as Name from 
customer c join payment p on c.customer_id = p.customer_id
join rental r on p.rental_id=r.rental_id
group by c.customer_id;

-- Question 12: List the titles of movies rented by each customer in a particular city (e.g., 'London').
select concat(c.first_name, ' ', c.last_name) As Customer,f.title
from customer c
join address a on c.address_id = a.address_id
join city ct on a.city_id = ct.city_id
join rental r on c.customer_id = r.customer_id
join inventory i on r.inventory_id = i.inventory_id
join film f on i.film_id = f.film_id
where ct.city ='London'
order by customer, f.title;

-- Question 13: Display the top 5 rented movies along with the number of times they've been rented.
select f.title, count(r.rental_id) As Total_num
from film f
join inventory i on f.film_id = i.film_id
join rental r on i.inventory_id = r.inventory_id
group by f.title 
order by Total_num desc
limit 5;

-- Question 14 : Determine the customers who have rented movies from both stores (store ID 1 and store ID 2)
select c.customer_id, c.first_name, c.last_name
FROM customer c
JOIN rental r ON c.customer_id = r.customer_id
JOIN inventory i ON r.inventory_id = i.inventory_id
WHERE i.store_id IN (1, 2)
GROUP BY c.customer_id
HAVING COUNT(DISTINCT i.store_id) = 2;











